Change license to GPLv3
SecUSo/privacy-friendly-todo-list pull request #129
Opened 2024-09-09 09:21 UTC by udenr

This PR fixes the issue with inconsistent licenses as decribed in #116

2024-09-09 11:06 UTC, coderPaddyS approved these changes

2024-09-09 12:17 UTC, 0xC0FFEEC0DE requested changes
I agree to the existing changes. But the following files also show Apache as license of the app:
- \app\src\main\res\values\strings.xml
- \app\src\main\res\values-nl\strings.xml

They should be changed too. See string with name "privacy_friendly".

2024-09-13 16:40 UTC, nico1509 approved these changes

2024-09-14 11:09 UTC, Kamuno approved these changes

2024-10-25 12:16 UTC, petermayer approved these changes

2024-10-25 12:16 UTC, merged